### ISSUE TITLE
Make `PROJECT_NAME` match the various casings so search and replace can be used

### ISSUE THREAD

**Issue by jeppester** [abtion/muffi#12]
Instead of having `PROJECT_NAME` everywhere, I think it would make sence to have:
- project_name (snake case)
- project-name (param case)
- ProjectName (pascal case)

Then when using the template, all occurrences can be easily search/replaced.
Later a script could be added for easily updating all the occurrences.

I'm adding this as an issue, so that I hopefully at some point will remember/be reminded to make a PR that improves the situation

**Comment by heatherm** [comment]
@jeppester can you add this to https://app.asana.com/0/1142794766483633/board so that we're just tracking stuff in one place

**Comment by jeppester** [comment]
Moved to Asana

**Comment by runephilosof-abtion** [comment]
Wrong link to Asana https://app.asana.com/0/1142794766483633/1152060241410857

**Comment by runephilosof-abtion** [comment]
Fixed in https://github.com/abtion/muffi/pull/19
