### ISSUE TITLE
What is this repo for?

### ISSUE THREAD

**Issue by bohme** [abtion/muffi#15]
Why are we using a static repo one has to copy over vs writing our own generator to generate a new app to our liking?
Who wants to manually search and replace `PROJECT_NAME` ?

In short this repo feels like a lot of manual work 🤔

**Comment by bohme** [comment]
I think we should let ourselves be inspired by something like [Suspenders](https://github.com/thoughtbot/suspenders) and create our own gem for generating new rails-apps.

So we could call it something like this:
```
muffi project-name
muffi project-name --heroku true --api true 
etc
```

Passing through the standard rails generator options as well as adding our own for a more automatic process.
This should also be easier to maintain in the long run 🤔

**Comment by prrrnd** [comment]
This question has been raised a few times, and I think everybody is leaning towards using the [Rails template API](https://guides.rubyonrails.org/rails_application_templates.html).

Using an already generated Rails application is a lower barrier for junior developers, and allows us to get quick feedback on what a template should contain.
Now that the team has gained experience, it totally makes sense to start considering the Rails template API. There is an upcoming IPM for this project, and I believe you are welcome to join if you wish to actively participate in its development. Join the #muffi channel if you are interested in the updates etc. 👍
